# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=26, validators=[django.core.validators.RegexValidator(message='Bank account must have 26 digits.', regex='^\\d{26}$')])),
                ('title', models.CharField(max_length=60)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
